### ISSUE TITLE
Elements long banner still needs to be swapped (above Ts&Cs)

### ISSUE THREAD

**Issue by ribenaberry** [anthb/envato-cm#19]
The banner "Cyber Monday Offer Just for you! $19/month" needs to be swapped out for the "8000+ fonts" (https://envato.slack.com/files/lindsay_a/F35R8B23A/cybermonday-elements--long2.jpg)

just checking on tracking

**Comment by ribenaberry** [comment]
?utm_source=landingpage&utm_medium=promos&utm_campaign=elements_envatocom_lp_cybermonday2016

**Comment by ribenaberry** [comment]
@jordanlewiz @anthb sorry, tile and banner both need tracking, this was only just picked up

**Comment by jordanlewiz** [comment]
Hey @ribenaberry we already have this tracking on Tiles `https://elements.envato.com/?_ga=1.40297254.588888245.1468279928` should we replace it?

**Comment by ribenaberry** [comment]
yes, apologies, this came from Roey and BI.
