### ISSUE TITLE
Collection links to updated link on TF, CC and GR

### ISSUE THREAD

**Issue by ribenaberry** [anthb/envato-cm#21]
Under **"View more discounted files"** 

Links need to go to...

[CC: ](https://codecanyon.net/collections/shared/8611dcee1ce8aab09d838fd2c0ce88d17d3499ce009917b3f0f7eb95b2edef81)
  
[GR: ](https://codecanyon.net/collections/shared/f03f247b2ac3e2a531f8299cfbdd1c77b138a7b14b31a539af819e88d19ecc02)

TF: (https://codecanyon.net/collections/shared/5ee5e8f49d266649e081a6d658e4397202f73e7c689cba6c454e2cd8e6af79f6)

**Comment by anthb** [comment]
merged
